### ISSUE TITLE
Add subscribe and unsubscribe for http events

### ISSUE THREAD

**Issue by judepereira** [microservices/microservice.guide#13]
**Spec:**
```yaml
http:
  port: 1000
  subscribe:
    endpoint:  /sub
    method: post
  unsubscribe:
    endpoint:  /unsub
    method: delete
```
