### ISSUE TITLE
Different lifecycle strategies for event based services

### ISSUE THREAD

**Issue by judepereira** [microservices/microservice.guide#14]
### Strategy 1 - Start the main app once at boot
```yaml
lifecycle:
  startup:
    command: foo
commands:
  bot:
    events:
      hears:
        arguments:
          pattern:
            type: string
        http:
          port: 5000
          subscribe:
            path: /subscribe
            method: post
```

### Strategy 2 - Start the app every time 
```yaml
commands:
  bot:
    run:
      command: foo
    arguments:
      ...
    events:
      hears:
        arguments:
          pattern:
            type: string
        http:
          port: 5000
          subscribe:
            path: /subscribe
            method: post
```

**Note:** If a command which emits events does not have the `run` section, then it cannot have `arguments` either, as these arguments cannot be delivered.
