### ISSUE TITLE
Enhance omg.yml to include properties and list/object structure

### ISSUE THREAD

**Issue by judepereira** [microservices/microservice.guide#23]
In the following example, the following new concepts have been introduced:

1. arguments.$.in - possible values - path, query, requestBody
2. http.subscribe.contentType - how to package the command request body from the Platform to the Service 
3. output.contentType - the content type of the output
3. output.properties - how to parse the response body from the given contentType
4. output.items - in the case of a list, what this list contains

```yaml
commands:
  bot:
    events:
      hears:
        arguments:
          pattern:
            type: string
            in: requestBody
        http:
          port: 5000
          subscribe:
            path: /subscribe
            method: post
            contentType: application/json
          unsubscribe:
            path: /unsubscribe
            method: delete
        output:
          contentType: application/json
          type: object
          properties:
            text:
              help: The message text
              type: string
  list_channels:
    http:
      port: 5000
      method: get
      path: /channels
    output:
      contentType: application/json
      type: list
      items:
        type: object
        properties:
          id:
            type: string
```
