### ISSUE TITLE
Classifying data

### ISSUE THREAD

**Issue by stevepeak** [microservices/microservice.guide#37]
The `output` data type is already identified as the class of data (ie `string`, `number` etc). There is another value classification of data: it's classification. For example if a service outputs user data (email,  name, etc).

> This feature could be used by a platform to understand (without guessing) more abut the data that is being returned from a service action. Examples range from identifying users, companies and products. 
> This can be used  for GDRP, removing sensitive data from logs, machine learning and more.

Example user classification.
```yaml
# Showing FullContact service as an example
actions:
  person:
    arguments:
      email:
        type: string
    output:
      type: map
      properties:
        name:
          type: string
          class: user.name  # Identify this data as a user's name
```

The OMG guide would be responsible to list all classifications for data in order to keep standardized.
