### ISSUE TITLE
Adding support for multipart/form-data

### ISSUE THREAD

**Issue by judepereira** [microservices/microservice.guide#48]
We need to facilitate the movement of data using the Content-Type multipart/form-data.

## Spec update
```yaml
actions:
  my_action:
    http:
      contentType: multipart/form-data
    arguments:
      my_argument:
        in: formBody
    output:
      type: form
      contentType: multipart/form-data
      properties:
        my_output:
          type: any
```

## What this adds support for
1. Support for making requests with the content type set to `multipart/form-data`
   1. Each argument will be sent as a form field
2. Support for reading responses from services with the content type set to `multipart/form-data`
   1. Each argument will be read as a form field

**Comment by wilzbach** [comment]
AFAICT the spec doesn't allow binary data as of now, so I think we first should add this to the spec before.

```yaml
actions:
  my_action:
    http:
      contentType: multipart/form-data
    arguments:
      my_file:
        in: formBody
        contentType: binary OR image/jpeg # <- this is missing
```

See e.g.
- https://tools.ietf.org/html/rfc2183
- https://swagger.io/docs/specification/describing-request-body/file-upload/

**Comment by judepereira** [comment]
@wilzbach - according to [this](https://microservice.guide/schema/actions/#actions), it should be as follows:
```yaml
arguments:
  my_file:
    in: formBody
    type: object
    contentType: */*
```

This is already supported in `output`, we can add it to the argument as well.
