### ISSUE TITLE
Data streams

### ISSUE THREAD

**Issue by wilzbach** [microservices/microservice.guide#49]
The spec should clarify how streaming support can be added in the schema and tooling. This is useful for:
- big files
- streams

- https://http2.github.io/http2-spec/#StreamsLayer
- https://en.wikipedia.org/wiki/Chunked_transfer_encoding

```yaml
actions:
  webcam:
    http:
      port: 8080
      method: get
      path: /webcam
      contentType: stream
```

Note that even Swagger doesn't support this fully as of now and simply uses `binary`.
Example: https://github.com/go-swagger/go-swagger/blob/master/examples/stream-server/swagger.yml
