### ISSUE TITLE
Define custom schemas

### ISSUE THREAD

**Issue by wilzbach** [microservices/microservice.guide#50]
It would be awesome to be able to define custom types for better documentation and error checking.
The engine could e.g. always ensure that the request and response match the spec. This will also help e.g. auto-completion and other static analysis checks.

Example:

```yaml
types:
   Size:
      - type: enum   # <- this is already supported, but one can't reuse the definition
      - values:
         - small
         - medium
         - large
   Customer:
      - type: struct
      - name: string
      - email: string # <- is this is fairly common, it could be its own primitive type
   Status:
      - type: enum
      - enum:
         - sucess
         - pending
         - cancelled
         - in_delievery
    Order:
       - type: struct
       - customer: Customer
       - status: Status

actions:
  make_coffee:
    arguments:
      customer:
        type: Customer
        in: requestBody
      size:
        type: string
        in: path
    output:
       type: Order
    http:
      port: 8080
      method: post
      path: /make_coffee/{size}
```

Enums are already supported and one could theoretically do:

```yaml
types:
   Size: &Size
      - type: enum
      - values:
         - small
         - medium
         - large
actions:
  make_coffee:
    arguments:
      customer:
        type: Customer
        in: requestBody
      size: *Size
```

Though imho it would be nicer to support schemas out of the box.

See also:

- https://en.wikipedia.org/wiki/Enumerated_type
- https://en.wikipedia.org/wiki/Composite_data_type
