### ISSUE TITLE
Reuse actions and set arguments

### ISSUE THREAD

**Issue by stevepeak** [microservices/microservice.guide#58]
Discovered a nifty trick that reduces duplication that I wanted to shed light on.

Below we have a `microservice.yml` that reuses the action `like` while setting one of the arguments to the properties of the event `tweets`.

```yaml
actions:
  like: &like
    arguments:
      tweetid:
        type: int
    output: null

  stream:
    events:
      tweets:
        output:
          properties:
            id:
              type: int
          actions:
            like: 
              <<: *like
              defaults:
                tweetid: id  # this "id" is the value of the property above
```

To help visualize this let's use Storyscript to show what it could looks like:

```coffee
when twitter stream tweets as tweet
    tweet like
```

There are many other use cases: `dropbox list files -> delete file`, `calendar search -> update/move event`, etc.

<details>
<summary>Here is the output when parsed by yaml</summary>

Notice how the action `like` is defaulted and the new key `set` is included in the output.

```json
{
  "actions": {
    "like": {
      "output": null, 
      "arguments": {
        "tweetid": {
          "type": "int"
        }
      }
    }, 
    "stream": {
      "events": {
        "tweet": {
          "output": {
            "properties": {
              "id": {
                "type": "int"
              }
            }, 
            "actions": {
              "like": {
                "output": null, 
                "set": {
                  "tweetid": "id"
                }, 
                "arguments": {
                  "tweetid": {
                    "type": "int"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

</details>
