### ISSUE TITLE
Environment check function

### ISSUE THREAD

**Issue by stevepeak** [microservices/microservice.guide#59]
Proposition to add methods for checking environment variables before deployment.

```yaml
environment:
  foobar:
    ...
environment_check: ["python", "check_env.py"]
```

All environment variables are included during the check (because they all may be needed). Return a `0` if the variable(s) are valid. Return a `1+` for failure and write to `stderr` why.
