### ISSUE TITLE
Introduce objects

### ISSUE THREAD

**Issue by stevepeak** [microservices/microservice.guide#60]
A service/function may produce an object output that has actions that returns the same object. This creates a circular reference in the yaml that is unable to resolve using `&obj` and `<<: *obj`

Introducing `objects` as a top level node would solve this.

```yaml
# microservice yaml for a recursive object usage
objects:
  foo:
    actions:
      bar:
        output: foo

actions:
  newFoo:
    output: foo
```

> Notice how the object `foo` is declared and then later used in the `output: foo` which points back to the parent object.
