### ISSUE TITLE
Lifecycle spec MAY contain "healthy" and "ready" commands

### ISSUE THREAD

**Issue by geovanisouza92** [microservices/microservice.guide#81]
It would be useful to describe healthchecks on lifecycle, which could be used by ocherstrators and load balancers.

```yaml
lifecycle:
  healthy:
    command: ...
    interval: 30
  ready:
    command: ...
    wait: 60
```
