### ISSUE TITLE
Docs for items

### ISSUE THREAD

**Issue by stevepeak** [microservices/microservice.guide#82]
The `items` key is not documented in the following example:

```yaml
actions:
  foo:
    arguments:
      bar:
        type: list
        items: 
            ???
```
