### ISSUE TITLE
Add support for objects in arguments

### ISSUE THREAD

**Issue by stevepeak** [microservices/microservice.guide#83]
An argument could be a `map` of data. The properties of the map could be defined in the following way.

```yaml
actions:
  foo:
    arguments:
      bar:
        type: map  # or this could be called object?
        properties:
          foo:
            type: string
```

> [Example usage](https://github.com/microservice/machinebox-classificationbox/blob/dab83f84198748685141cfdc244276b4761eec3d/microservice.yml#L32-L42)
