### ISSUE TITLE
Using yaml variables and references

### ISSUE THREAD

**Issue by stevepeak** [microservices/microservice.guide#85]
Add some docs for helping users understand yaml var/refs. Like this 😄 

```yaml
foo: &myRef
  - 1
  # ...
  - 2

bar:
  <<: *myRef
```

This is one of many Yaml tricks that the OMG should illuminate.
